// Control 
export const TOGGLE_ADD_TODO = 'TOGGLE_ADD_TODO'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

// Todos
export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'

// Todo
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS'
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

// Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
// Logout
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE'